# Generated by Django 2.0.6 on 2018-06-22 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bracket', '0001_initial'), ('bracket', '0002_auto_20180619_0803'), ('bracket', '0003_group_groupteam_match_pick'), ('bracket', '0004_match_winner_date_unique')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=400)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=1)),
                ('group_stage_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_finals', models.BooleanField(default=False)),
                ('semi_finals', models.BooleanField(default=False)),
                ('finals', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(verbose_name='date submitted')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='GroupTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Group')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='bracket.Team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='bracket.Team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='bracket.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='bracket.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default='2018-06-22 00:00:00', help_text='Match kickoff time (UTC)', verbose_name='kickoff'),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('grp', 'Group Stage'), ('qts', 'Quarterfinal'), ('sem', 'Semifinal'), ('fin', 'Final')], default='grp', max_length=3),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_penalty',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team1_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_penalty',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='team2_score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('team1', 'team2')},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='logo',
            new_name='flag',
        ),
        migrations.RemoveField(
            model_name='team',
            name='group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='team',
            name='secondary_color',
        ),
        migrations.AddField(
            model_name='team',
            name='emoji_string',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='fifa_code',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
