# Generated by Django 2.0.6 on 2018-06-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=400)),
                ('primary_color', models.CharField(max_length=50)),
                ('secondary_color', models.CharField(max_length=50)),
                ('group', models.CharField(max_length=1)),
                ('group_stage_rank', models.IntegerField(default=0)),
                ('quarter_finals', models.BooleanField(default=False)),
                ('semi_finals', models.BooleanField(default=False)),
                ('finals', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
    ]
