# Generated by Django 2.0.6 on 2018-06-19 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_finals', models.BooleanField(default=False)),
                ('semi_finals', models.BooleanField(default=False)),
                ('finals', models.BooleanField(default=False)),
                ('winner', models.BooleanField(default=False)),
                ('entry_date', models.DateTimeField(verbose_name='date submitted')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='finals',
        ),
        migrations.RemoveField(
            model_name='team',
            name='quarter_finals',
        ),
        migrations.RemoveField(
            model_name='team',
            name='semi_finals',
        ),
        migrations.RemoveField(
            model_name='team',
            name='winner',
        ),
        migrations.AddField(
            model_name='teamrank',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Team'),
        ),
    ]
