# Generated by Django 2.0.6 on 2018-06-22 12:30

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0004_match_winner_date_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('grp', 'Group Stage'), ('r16', 'Round of 16'), ('qts', 'Quarterfinal'), ('sem', 'Semifinal'), ('fin', 'Final')], default='grp', max_length=3),
        ),
        migrations.AddField(
            model_name='team',
            name='group_goals_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='group_goals_scored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='group_draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='group_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='group_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GroupPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Match')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bracket.Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Knockout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='KnockoutPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='pick',
            name='match',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='team',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='user',
        ),
        migrations.CreateModel(
            name='RoundOf16',
            fields=[
                ('knockout_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bracket.Knockout')),
                ('seed1', models.IntegerField(choices=[(1, 'Winner'), (2, 'Runner-up')], default=1)),
                ('seed2', models.IntegerField(choices=[(1, 'Winner'), (2, 'Runner-up')], default=1)),
                ('group1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1_group', to='bracket.Group')),
                ('group2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2_group', to='bracket.Group')),
            ],
            bases=('bracket.knockout',),
        ),
        migrations.DeleteModel(
            name='Pick',
        ),
        migrations.AddField(
            model_name='knockoutpick',
            name='knockout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bracket.Knockout'),
        ),
        migrations.AddField(
            model_name='knockoutpick',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bracket.Team'),
        ),
        migrations.AddField(
            model_name='knockoutpick',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knockout',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='bracket.Match'),
        ),
        migrations.AddField(
            model_name='knockout',
            name='prev_match1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_match_1', to='bracket.Knockout'),
        ),
        migrations.AddField(
            model_name='knockout',
            name='prev_match2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_match_2', to='bracket.Knockout'),
        ),
    ]
