# Generated by Django 2.0.6 on 2018-06-22 01:12

from django.db import migrations
from ..data_setup import create, revert


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0004_match_winner_date_unique'),
    ]

    operations = [
        migrations.RunPython(create, revert)
    ]
