# Generated by Django 2.0.6 on 2018-06-23 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracket', '0006_data_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 19, 0), help_text='Match kickoff time (UTC)', verbose_name='kickoff'),
        ),
    ]
