from django.db import models

class Team(models.Model):
    counry = models.CharField(max_length=50)
    #path to image?
    logo = models.CharField(max_length=400) 
    primary_color = models.CharField(max_length=50)
    secondary_color = models.CharField(max_length=50)

class Bracket(models.Model):
    one_c = models.ForeignKey(Team)
    two_d = models.ForeignKey(Team)
    one_a = models.ForeignKey(Team)
    two_b = models.ForeignKey(Team)
    one_b = models.ForeignKey(Team)
    two_a = models.ForeignKey(Team)
    one_d = models.ForeignKey(Team)
    two_c = models.ForeignKey(Team)
    one_e = models.ForeignKey(Team)
    two_f = models.ForeignKey(Team)
    one_g = models.ForeignKey(Team)
    two_h = models.ForeignKey(Team)
    one_f = models.ForeignKey(Team)
    two_e = models.ForeignKey(Team)
    one_h = models.ForeignKey(Team)
    two_2 = models.ForeignKey(Team)
    quarter_1 = models.ForeignKey(Team)
    quarter_2 = models.ForeignKey(Team)
    quarter_3 = models.ForeignKey(Team)
    quarter_4 = models.ForeignKey(Team)
    quarter_5 = models.ForeignKey(Team)
    quarter_6 = models.ForeignKey(Team)
    quarter_7 = models.ForeignKey(Team)
    quarter_8 = models.ForeignKey(Team)
    semi_1 = models.ForeignKey(Team)
    semi_2 = models.ForeignKey(Team)
    semi_3 = models.ForeignKey(Team)
    semi_4 = models.ForeignKey(Team)
    finals_1 = models.ForeignKey(Team)
    finals_2 = models.ForeignKey(Team)
    winner = models.ForeignKey(Team)
    entry_date = models.DateTimeField('date submitted')
